project_id = "soqesuykbgriweanllzo"

[functions.generate-permit-pdf]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.check-sla-breach]
verify_jwt = false

[functions.verify-signature-approval]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false
